=== OlaWrobe/Solvd-database/mydbProject/src/main/resources/parsers/olympics.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="olympics">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sports" type="sports"/>
                <xs:element name="teams" type="teams"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="sports">
        <xs:sequence>
            <xs:element name="sport" type="sport" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sport">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="sportType" type="sportType"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sportType">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="isIndividual" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="participant">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="country" type="country"/>
            <xs:element name="sport" type="sport"/>
            <xs:element name="pname" type="xs:string"/>
            <xs:element name="surname" type="xs:string"/>
            <xs:element name="birthdate" type="xs:date"/>
            <xs:element name="gender" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="individualScoreList" type="individualScoreList"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="country">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="countryName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="individualScoreList">
        <xs:sequence>
            <xs:element name="individualScore" type="individualScore" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="individualScore">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="time" type="xs:time"/>
            <xs:element name="points" type="xs:int"/>
            <xs:element name="distance" type="xs:float"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="teams">
        <xs:sequence>
            <xs:element name="team" type="team"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="captain">
        <xs:sequence>
            <xs:element name="participant" type="participant"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="players">
        <xs:sequence>
            <xs:element name="participant" type="participant" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="teamScoreList">
        <xs:sequence>
            <xs:element name="teamScore" type="teamScore" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="teamScore">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="teamPoints" type="xs:int"/>
            <xs:element name="teamTime" type="xs:time"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="team">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="country" type="country"/>
            <xs:element name="captain" type="captain"/>
            <xs:element name="teamName" type="xs:string"/>
            <xs:element name="squadSize" type="xs:int"/>
            <xs:element name="players" type="players"/>
            <xs:element name="teamScoreList" type="teamScoreList"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== OlaWrobe/Solvd-database/mydbProject/src/main/resources/parsers/olympics.xml
<olympics xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="olympics.xsd">
    <sports>
        <sport>
            <id>1</id>
            <sportType>
                <id>1</id>
                <name>SportType1</name>
                <isIndividual>true</isIndividual>
            </sportType>
            <name>Sport1</name>
            <description>Description1</description>
        </sport>
        <sport>
            <id>2</id>
            <sportType>
                <id>2</id>
                <name>SportType2</name>
                <isIndividual>false</isIndividual>
            </sportType>
            <name>Sport2</name>
            <description>Description2</description>
        </sport>
    </sports>
    <teams>
        <team>
            <id>1</id>
            <country>
                <id>1</id>
                <countryName>Country1</countryName>
            </country>
            <captain>
                <participant>
                    <id>1</id>
                    <country>
                        <id>1</id>
                        <countryName>Country1</countryName>
                    </country>
                    <sport>
                        <id>1</id>
                        <sportType>
                            <id>1</id>
                            <name>SportType1</name>
                            <isIndividual>true</isIndividual>
                        </sportType>
                        <name>Sport1</name>
                        <description>Description1</description>
                    </sport>
                    <pname>Participant1</pname>
                    <surname>Surname1</surname>
                    <birthdate>2000-01-01</birthdate>
                    <gender>Male</gender>
                    <email>participant1@example.com</email>
                    <individualScoreList>
                        <individualScore>
                            <id>1</id>
                            <time>10:10:10</time>
                            <points>2</points>
                            <distance>0.0</distance>
                        </individualScore>
                        <individualScore>
                            <id>2</id>
                            <time>00:00:00</time>
                            <points>4</points>
                            <distance>0.0</distance>
                        </individualScore>
                    </individualScoreList>
                </participant>
            </captain>
            <teamName>Team1</teamName>
            <squadSize>20</squadSize>
            <players>
                <participant>
                    <id>1</id>
                    <country>
                        <id>1</id>
                        <countryName>Country1</countryName>
                    </country>
                    <sport>
                        <id>1</id>
                        <sportType>
                            <id>1</id>
                            <name>SportType1</name>
                            <isIndividual>true</isIndividual>
                        </sportType>
                        <name>Sport1</name>
                        <description>Description1</description>
                    </sport>
                    <pname>Participant1</pname>
                    <surname>Surname1</surname>
                    <birthdate>2000-01-01</birthdate>
                    <gender>Male</gender>
                    <email>participant1@example.com</email>
                    <individualScoreList>
                        <individualScore>
                            <id>1</id>
                            <time>00:00:00</time>
                            <points>2</points>
                            <distance>0.0</distance>
                        </individualScore>
                        <individualScore>
                            <id>2</id>
                            <time>01:01:01</time>
                            <points>4</points>
                            <distance>0.0</distance>
                        </individualScore>
                    </individualScoreList>
                </participant>
                <participant>
                    <id>2</id>
                    <country>
                        <id>2</id>
                        <countryName>Country2</countryName>
                    </country>
                    <sport>
                        <id>2</id>
                        <sportType>
                            <id>2</id>
                            <name>SportType2</name>
                            <isIndividual>false</isIndividual>
                        </sportType>
                        <name>Sport2</name>
                        <description>Description2</description>
                    </sport>
                    <pname>Participant2</pname>
                    <surname>Surname2</surname>
                    <birthdate>1995-05-15</birthdate>
                    <gender>Female</gender>
                    <email>participant2@example.com</email>
                    <individualScoreList>
                        <individualScore>
                            <id>3</id>
                            <time>02:02:20</time>
                            <points>3</points>
                            <distance>0.0</distance>
                        </individualScore>
                        <individualScore>
                            <id>4</id>
                            <time>02:02:02</time>
                            <points>5</points>
                            <distance>0.0</distance>
                        </individualScore>
                    </individualScoreList>
                </participant>
            </players>
            <teamScoreList>
                <teamScore>
                    <id>1</id>
                    <teamPoints>100</teamPoints>
                    <teamTime>00:15:30</teamTime>
                </teamScore>
                <teamScore>
                    <id>2</id>
                    <teamPoints>75</teamPoints>
                    <teamTime>00:20:45</teamTime>
                </teamScore>
            </teamScoreList>
        </team>
    </teams>
</olympics>
